name: Frontend unit tests

on:
  push:
    branches:
      - master
    paths:
      - 'web/html/src/**'
      - '.github/workflows/frontend-unit-tests.yml'
  pull_request:
    paths:
      - 'web/html/src/**'
      - '.github/workflows/frontend-unit-tests.yml'

jobs:
  frontend_unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 #v5.0.0
      with:
        node-version: ${{ matrix.node-version }}

    # See https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching
    - name: Use cached NPM dependencies
      id: cache-node-modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      name: List cache misses
      continue-on-error: true
      run: npm list

    - name: Install production dependencies
      run: npm ci --ignore-scripts --save=false

    - name: Run tests
      run: npm run test -- --no-cache
      env:
        BABEL_ENV: 'test'
